name: rxdart_ext_example
description: rxdart_ext_example
publish_to: none
version: 0.2.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  rxdart_ext: any
  rxdart: ^0.27.4

dependency_overrides:
  rxdart_ext:
    path: ../../rxdart_ext