name: rxdart_ext
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.2 <2.11.0'

dependencies:
  rxdart:
    git:
      url: https://github.com/ReactiveX/rxdart.git
      ref: nnbd

dev_dependencies:
  pedantic: ^1.10.0-nullsafety
  test: ^1.16.0-nullsafety.4
