name: rxdart_ext
description: Some extension methods and classes built on top of RxDart - RxDart extension.
version: 0.0.1-nullsafety.4
author: Petrus Nguyễn Thái Học <hoc081098@gmail.com>
homepage: https://github.com/hoc081098/rxdart_ext.git
repository: https://github.com/hoc081098/rxdart_ext.git
issue_tracker: https://github.com/hoc081098/rxdart_ext/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  rxdart: ^0.26.0-nullsafety.1
  meta: ^1.3.0-nullsafety.6

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.12
  collection: ^1.15.0-nullsafety.5
  mockito: ^5.0.0-nullsafety.5
  build_runner: ^1.11.0

#  pub run build_runner build --delete-conflicting-outputs --enable-experiment=non-nullable