name: check_urls
description: Check if the urls in README.md are valid
version: 1.0.0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  http: 0.13.5
dependency_overrides:
  rxdart: 0.0.1
dependency_overrides:
  rxdart: 0.0.1
dependency_overrides:
  rxdart: 0.0.1
